# Generated by Django 3.2.5 on 2021-08-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dp', models.ImageField(upload_to=None)),
                ('photo', models.ImageField(upload_to=None)),
                ('location', models.IntegerField()),
                ('mobileno', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('callAllowedTiming', models.CharField(max_length=50)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomId', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('roomArea', models.CharField(max_length=50)),
                ('rent', models.IntegerField()),
                ('ownerid', models.IntegerField()),
                ('photos', models.ImageField(upload_to=None)),
                ('maxAllowedPersonCount', models.IntegerField()),
                ('roomstatus', models.BooleanField()),
                ('gfbfAllowed', models.BooleanField()),
                ('balkiniStatus', models.BooleanField()),
                ('waterAvailability', models.BooleanField()),
                ('OneBathroomSharedBy', models.IntegerField()),
                ('OnWhichFloor', models.IntegerField()),
                ('totalBathroom', models.IntegerField()),
                ('totalBulbHolder', models.IntegerField()),
                ('totalPlug', models.IntegerField()),
                ('totalAlmirah', models.IntegerField()),
                ('totalFans', models.IntegerField()),
                ('totalwindows', models.IntegerField()),
                ('totalChairs', models.IntegerField()),
                ('totalTables', models.IntegerField()),
                ('totalBed', models.IntegerField()),
                ('pastReviews', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=50)),
                ('Id', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dp', models.ImageField(upload_to=None)),
                ('photo', models.ImageField(upload_to=None)),
                ('mobileno', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('aadharNo', models.CharField(max_length=13)),
                ('aadharPhoto', models.ImageField(upload_to=None)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
