# Generated by Django 3.2.5 on 2021-08-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to='pics')),
                ('startingdate', models.DateField()),
                ('endingdate', models.DateField()),
                ('techused', models.CharField(max_length=50)),
                ('desc', models.TextField()),
            ],
        ),
    ]
