# Generated by Django 3.2.5 on 2021-08-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('username', models.CharField(default='xyz', editable=False, max_length=122, primary_key=True, serialize=False)),
                ('firstname', models.CharField(default='xyz', editable=False, max_length=122)),
                ('lastname', models.CharField(default='xyz', editable=False, max_length=122)),
                ('email', models.EmailField(default='xyz', editable=False, max_length=122)),
                ('password', models.CharField(default='xyz', editable=False, max_length=20)),
                ('phone', models.BigIntegerField(default='xyz', editable=False)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
