# Generated by Django 3.2.5 on 2021-08-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauthapp', '0003_auto_20210804_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(default='xyz@gmail.com', max_length=122),
        ),
    ]
