# Generated by Django 3.2.5 on 2021-08-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('name', models.CharField(default='xyz', editable=False, max_length=122)),
                ('email', models.EmailField(default='xyz', editable=False, max_length=122, primary_key=True, serialize=False)),
                ('phone', models.BigIntegerField(default='xyz', editable=False)),
                ('desc', models.TextField(default='xyz', editable=False)),
                ('date', models.DateField(default='xyz', editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.IntegerField(default='', primary_key=True, serialize=False)),
                ('subject', models.CharField(default='xyz', max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('offer', models.BooleanField()),
            ],
        ),
    ]
