# Generated by Django 3.2.5 on 2021-08-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turistingo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turistingo',
            name='dis',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='turistingo',
            name='offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turistingo',
            name='price',
            field=models.IntegerField(default=10000),
        ),
    ]
